name = "touban-bot"
main = "src/index.ts"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]

[vars]
TOUBAN_NAME = "XX当番"
TOUBAN_MEMBERS = "メンバー1,メンバー2,メンバー3"
TOUBAN_DESCRIPTION = "<当番の説明>"

[triggers]
crons = ["0 22 * * *"]
